modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/BetterRandomSourceConcurrencyCrash"

[[mods]]
    modId="better_randomsource_concurrency_crash"
    version="${mod_version}"
    displayName="BetterRandomSourceConcurrencyCrash"
    displayURL="https://curseforge.com/minecraft/mc-mods/betterrandomsourceconcurrencycrash"
    authors="XFactHD"
    displayTest="IGNORE_ALL_VERSION"
    description=''''''

[[mixins]]
    config="better_randomsource_concurrency_crash.mixins.json"

[[dependencies.better_randomsource_concurrency_crash]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_randomsource_concurrency_crash]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
